### 1️⃣ Student Marks Analyzer

**What to build**

- Store marks of students in a 2D NumPy array
- Calculate:
    - Average marks per student
    - Subject-wise highest & lowest
    - Overall topper

**NumPy concepts**

- `ndarray`
- `axis`
- `mean()`, `max()`, `min()`
- Boolean indexing

👉 *Upgrade idea*: Add grading (A/B/C) using conditions.

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 2.1 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.9 MB 2.5 MB/s eta 0:00:05
   ---- ----------------------------------- 1.6/12.9 MB 2.3 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.9 MB 2.2 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.9 MB 2.1 MB/s eta 0:00:06
   --------- ------------------------------ 3.1/12.9 MB 2.3 MB/s eta 0:00:05
   ----------- ---------------------------- 3.7/12.9 MB 2.4 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.9 MB 2.9 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.9 MB 3.3 MB/s eta 0:00:03
   ------------------------- -------------- 8.1/12.9 MB 3.8 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.9 MB 4.0 MB/s eta 0:00:01
   ----------

In [4]:
import numpy as np

In [5]:
student_marks=np.array([[80,85,90],
                        [90,79,89],
                        [99,89,79],
                        [95,99,89],
                        [80,69,87]])
print(student_marks)

[[80 85 90]
 [90 79 89]
 [99 89 79]
 [95 99 89]
 [80 69 87]]


In [6]:
print(student_marks.shape)
print(student_marks.ndim)
print(student_marks.size)

(5, 3)
2
15


In [19]:
avg_marks=np.mean(student_marks,axis=1)
print(f"Average marks of each student:{avg_marks.astype(int)}")

Average marks of each student:[85 86 89 94 78]


In [21]:
min_marks=np.min(student_marks,axis=0)
print(f"Minimum marks of each subject:{min_marks}")

Minimum marks of each subject:[80 69 79]


In [22]:
max_marks=np.max(student_marks,axis=0)
print(f"Maximum marks of each subject:{max_marks}")

Maximum marks of each subject:[99 99 90]


In [24]:
topper=np.max(np.sum(student_marks,axis=1))
print(f"Topper of the class:{topper}")

Topper of the class:283


In [33]:
sum=np.sum(student_marks,axis=1)
print(f"Total marks of each student:{sum}")

Total marks of each student:[255 258 267 283 236]


In [43]:
for i in range(len(avg_marks)):
    print(f"Average marks of student {i+1}:{avg_marks[i].astype(int)}")
    if (avg_marks[i] >= 90):
        print("Grade:A")
    elif (avg_marks[i] >=80):
        print("Grade:B")
    elif (avg_marks[i] >=70):
        print("Grade:C")
    else:
        print("Grade:D")

Average marks of student 1:85
Grade:B
Average marks of student 2:86
Grade:B
Average marks of student 3:89
Grade:B
Average marks of student 4:94
Grade:A
Average marks of student 5:78
Grade:C
