### 2️⃣ Temperature Data Analysis

**What to build**

- Daily temperature data for a month
- Find:
    - Hottest & coldest day
    - Weekly average temperature
    - Days above average

**NumPy concepts**

- Slicing
- `where()`
- Aggregations
- Reshaping

In [1]:
import numpy as np

In [28]:
# Daily temperatures (°C) for 30 days
temps = np.array([
    28, 30, 29, 31, 32, 33, 34,
    35, 36, 34, 33, 32, 31, 30,
    29, 28, 27, 26, 28, 29,
    30, 31, 32, 33, 34, 35,
    36, 37, 38, 39
])
print("Daily temperature data for a month:")

days=np.arange(1,31)
for day,temp in zip(days,temps):
    print(f"Day {day}: {temp}°C")





Daily temperature data for a month:
Day 1: 28°C
Day 2: 30°C
Day 3: 29°C
Day 4: 31°C
Day 5: 32°C
Day 6: 33°C
Day 7: 34°C
Day 8: 35°C
Day 9: 36°C
Day 10: 34°C
Day 11: 33°C
Day 12: 32°C
Day 13: 31°C
Day 14: 30°C
Day 15: 29°C
Day 16: 28°C
Day 17: 27°C
Day 18: 26°C
Day 19: 28°C
Day 20: 29°C
Day 21: 30°C
Day 22: 31°C
Day 23: 32°C
Day 24: 33°C
Day 25: 34°C
Day 26: 35°C
Day 27: 36°C
Day 28: 37°C
Day 29: 38°C
Day 30: 39°C


In [31]:
#Hottest & coldest
hottest_day=np.argmax(temps)
print(f"hottest day {hottest_day+1}: {temps[hottest_day]}°C")

coldest_day=np.argmin(temps)
print(f"coldest day {coldest_day+1}: {temps[coldest_day]}°C")



hottest day 30: 39°C
coldest day 18: 26°C


In [32]:
#Weekly average temperature
weekly_avg=temps.reshape((6,5))
print(weekly_avg)
print(f"weekly average temperature: {np.mean(weekly_avg,axis=1)}")

[[28 30 29 31 32]
 [33 34 35 36 34]
 [33 32 31 30 29]
 [28 27 26 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
weekly average temperature: [30.  34.4 31.  27.6 32.  37. ]


In [35]:
#Days above average
monthly_avg=np.mean(temps)
above_avg_days=np.where(temps>monthly_avg)[0]
print(f"Monthly Average:{monthly_avg}")

for i in above_avg_days:
    print(f"Day {i+1}: {temps[i]}°C")

Monthly Average:32.0
Day 6: 33°C
Day 7: 34°C
Day 8: 35°C
Day 9: 36°C
Day 10: 34°C
Day 11: 33°C
Day 24: 33°C
Day 25: 34°C
Day 26: 35°C
Day 27: 36°C
Day 28: 37°C
Day 29: 38°C
Day 30: 39°C
